"""Generator transition model estimation.

Estimates p01 = P(Y_{t+1}=1 | Y_t=0, action=g) and
p10 = P(Y_{t+1}=0 | Y_t=1, action=g) for each generator arm g.
"""

from __future__ import annotations

from dataclasses import dataclass

from abbo.realworld.candidate_bank.schema import CandidateManifest


@dataclass
class TransitionModel:
    """Transition probabilities for a generator arm."""

    arm: str
    p01: float  # P(Y_{t+1}=1 | Y_t=0, action=g)
    p10: float  # P(Y_{t+1}=0 | Y_t=1, action=g)
    n_from_incorrect: int = 0
    n_from_correct: int = 0


def estimate_transitions(
    parent_child_pairs: list[tuple[CandidateManifest, CandidateManifest]],
    arm: str,
    laplace_alpha: float = 1.0,
) -> TransitionModel:
    """Estimate transition probabilities from parent-child candidate pairs.

    Each pair is (parent_candidate, child_candidate) where the child was
    generated by the given arm from the parent.
    """
    n_0_to_1 = 0  # parent incorrect, child correct
    n_0_to_0 = 0  # parent incorrect, child incorrect
    n_1_to_0 = 0  # parent correct, child incorrect
    n_1_to_1 = 0  # parent correct, child correct

    for parent, child in parent_child_pairs:
        if child.generator_arm != arm:
            continue

        p_correct = parent.verifier_outputs.full_suite_pass or False
        c_correct = child.verifier_outputs.full_suite_pass or False

        if not p_correct:
            if c_correct:
                n_0_to_1 += 1
            else:
                n_0_to_0 += 1
        else:
            if c_correct:
                n_1_to_1 += 1
            else:
                n_1_to_0 += 1

    n_from_0 = n_0_to_0 + n_0_to_1
    n_from_1 = n_1_to_0 + n_1_to_1

    # Laplace smoothing
    p01 = (n_0_to_1 + laplace_alpha) / (n_from_0 + 2 * laplace_alpha)
    p10 = (n_1_to_0 + laplace_alpha) / (n_from_1 + 2 * laplace_alpha)

    return TransitionModel(
        arm=arm,
        p01=p01,
        p10=p10,
        n_from_incorrect=n_from_0,
        n_from_correct=n_from_1,
    )
